### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by tejashah88** [alexa-js/alexa-verifier-middleware#11]
Might be a good idea to add code coverage to keep consistency with all the other alexa-js libraries.

**Comment by dblock** [comment]
Go for it!

**Comment by tejashah88** [comment]
Since I'm not in control of adding code coverage from coveralls.io, here's a [link](https://github.com/nickmerwin/node-coveralls#tap) to see how to set it up.

**Comment by dblock** [comment]
You still have to do the code, see https://github.com/alexa-js/alexa-app-server/pull/29. I can enable it with a click after.

**Comment by tejashah88** [comment]
Resolved with #13.
