### ISSUE TITLE
Middleware should only check POST requests

### ISSUE THREAD

**Issue by tejashah88** [alexa-js/alexa-verifier-middleware#12]
Re-directed from [here](https://github.com/alexa-js/alexa-app/pull/144#discussion_r99015211)

One issue that I just found while testing is that when you do a GET request and the `alexa-verifier-middleware` is enabled with strict header checking, it gives me a 401 error, which shouldn't happen at all.

One possible fix is that the alexa-verifier-middleware should check what request method is being sent and if it is a POST request, then process the request accordingly. Here is a way to access the request's method from expressjs.

**Comment by mreinstein** [comment]
@tejashah88 I think this supposed to be an issue for `alexa-app`

**Comment by dblock** [comment]
Closed via https://github.com/alexa-js/alexa-app/pull/145.
