### ISSUE TITLE
not working with german special chars

### ISSUE THREAD

**Issue by chanzler** [alexa-js/alexa-verifier-middleware#22]
This middleware doesn't seem to work with german special chars like äöüÄÖÜß.

Example:
"intent": {
      "name": "GetWord",
      "slots": {
        "Keyword": {
          "name": "Keyword",
          "value": "änderung"
       }
    }
 }

**Comment by dblock** [comment]
Are you sure it's a middleware issue @chanzler? Define "doesn't work"? Try to write a test that reproduces your problem?

**Comment by chanzler** [comment]
I found the error. It was due to an old node js version. Thanks and keep it up.
