### ISSUE TITLE
Signatures not properly verified with german umlauts

### ISSUE THREAD

**Issue by arthurbrack** [alexa-js/alexa-verifier-middleware#24]
Hi,

I'm implementing a custom skill for alexa (german language). If recognized slots contain german umlauts (i.e. Küche), then the signature can not be verified.

I've fixed the problem, if I explicitly use Buffer with a given encoding und pass a Buffer object to the verifier.
...
  var bodyData = [];
  req.on('data', function(data) {
    bodyData.push(new Buffer(data, "utf8")); 
    req.rawBody += data;
  })
...
verifier(certUrl, signature, Buffer.concat(bodyData), function(er) {
....
}

BTW: I'm using Node.js 4.2 on my Synology NAS (a newer version is not available).

Regards
Arthur

**Comment by dblock** [comment]
This was already fixed, https://github.com/mreinstein/alexa-verifier/issues/19, can you check which version of alexa-verifier you're getting?

Also kudos on running this on a NAS! :)

**Comment by arthurbrack** [comment]
I've updated alexa-verifier and now it works :-)

thanks.
