### ISSUE TITLE
update alexa-verifier to 0.4.0

### ISSUE THREAD

**Issue by mreinstein** [alexa-js/alexa-verifier-middleware#26]
`alexa-verifier` is hardcoded to `0.3.3`. More recent versions of the module break the unit tests:
* changed the callback function to always be asynchronous in 0.3.4 and up
* changed some of the error messages to be more descriptive

Need to fix these issues before updating to the new version.

**Comment by tejashah88** [comment]
@mreinstein I just pushed the latest code with the updated dependencies and the tests are passing with flying colors! Anything else to be done before updating to the new version?

**Comment by mreinstein** [comment]
@tejashah88 LGTM. I just pushed some very minor tweaks. Good to go IMO.

thanks for knocking this out!

**Comment by tejashah88** [comment]
Published as version 0.3.0.
