### ISSUE TITLE
Would you like to move this repo into the alexa-js organization?

### ISSUE THREAD

**Issue by dblock** [alexa-js/alexa-verifier-middleware#3]
Would you like to move this repo into the newly created alexa-js organization, https://github.com/alexa-js? 

This would reduce bus factor as currently only @tejashah88 can add contributors to this project. By moving org admins can at least add new people, currently that's @matt-kruse and myself.

If you do want to do this, because Github requires one be admin of both source and destination, transfer the repo to me (@dblock) and I'll immediately move it to the org.

**Comment by tejashah88** [comment]
Sounds good. Transfer initiated.

**Comment by dblock** [comment]
Done. Welcome! You might want to add me and @matt-kruse to npm as well, but up to you.
