### ISSUE TITLE
v2 plan

### ISSUE THREAD

**Issue by mreinstein** [alexa-js/alexa-verifier-middleware#35]
Here's what I'm thinking about for the next major release (2.0.0):

* require node v12.17 and up
* switch to pure es module
* drop commonjs
* switch to es6 everywhere (`const`, `let`, `spread`, `destructuring`,  etc.)
* update all deps

These are just my current musings. Open for thoughts/ideas/suggestions.

**Comment by dblock** [comment]
typescript?

**Comment by tejashah88** [comment]
@mreinstein Sounds good! Has the `alexa-verifier` dependency been updated to support ES styled importing?

@dblock Good suggestion, although I'll admit that I'm not familiar with TS myself.

**Comment by mreinstein** [comment]
> Has the alexa-verifier dependency been updated to support ES styled importing?

I haven't yet, but there's a similar task open for it https://github.com/mreinstein/alexa-verifier/issues/65

**Comment by mreinstein** [comment]
Well it took me a while but there's finally a PR for this https://github.com/alexa-js/alexa-verifier-middleware/pull/42

If any of you want to take a look and provide feedback, now's the chance @dblock @tejashah88
