### ISSUE TITLE
better documentation around strictHeaderCheck

### ISSUE THREAD

**Issue by mreinstein** [alexa-js/alexa-verifier-middleware#4]
@tejashah88 some problems with the current README:

* There is a lot of content, and it's getting cluttered and hard to read
* the 2nd example showing `strictHeaderCheck` explains how to use that option, but no explanation of *why* someone should use it.
* the 1st example (simple usage) should probably be discouraged since it's arguably a little less secure

my suggestion is we just have one usage example, the `express` `router` one and explain why. Happy to send a PR to make these changes, just wanted to run it by you and see what you think. thoughts?

**Comment by tejashah88** [comment]
Sure, go ahead!
