### ISSUE TITLE
Migrate public repositories from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by tejashah88** [alexa-js/alexa-verifier-middleware#43]
Starting June 15th, it seems that Travis is not providing free services for open source projects in favor of a more commercial pricing plan. We'll need to find an alternate CI service that has the same free plan for open source projects (unless we want to bite the bullet for paying).

**Comment by tejashah88** [comment]
Actually scratch that, Travis does still support open source projects, but the owner of the alexa-js organization needs to migrate the public repositories. @dblock I'm not sure if you're the admin but can you take a look into this?

**Comment by mreinstein** [comment]
switched to github actions. resolved via https://github.com/alexa-js/alexa-verifier-middleware/commit/306ce48eb2781abf0f9b6167e3a217be80106272

**Comment by dblock** [comment]
Is there more to do? I've invited @mreinstein to co-own the org, and changed your permissions @tejashah88, since I haven't worked on this stuff recently at all - party on. FYI @matt-kruse is also an org owner.

**Comment by tejashah88** [comment]
@dblock Given the recent success with GitHub actions, it may be worth migrating to that from TravisCI for all our Alexa-JS repos. I personally don't have as much time but if I get more free time, I could look more into GitHub actions

**Comment by mreinstein** [comment]
>  if I get more free time, I could look more into GitHub actions

It's already done for alexa-verifier-middleware.  It's literally just a matter of copying the `.github/` directory into each repo where it's expected to run. 

The optional but nice to have extra steps:
* update `README.md` to render the github actions badge rather than travis
* remove `.travis.yml`

**Comment by tejashah88** [comment]
Oh, in that case I'll start migrating!

**Comment by mreinstein** [comment]
the github actions badge, I have been using this:

```markdown
![tests](https://github.com/mreinstein/alexa-verifier/actions/workflows/main.yml/badge.svg)
```

just substitute `mreinstein/alexa-verifier` with whatever account/repo you want to embed this in and it seems to work
