### ISSUE TITLE
Requests from alexa already behave like they are parsed

### ISSUE THREAD

**Issue by EeeDotZee** [alexa-js/alexa-verifier-middleware#45]
I've experienced the problem that i was running into the 'The raw request body has already been parsed' error message but only when the request was coming from Alexa (in my case the simulator)

I made this workaround which works but i think it's really hacky and I'm still wondering why my Alexa message behaves like that?

```js
   if (req._body) {
    //Requests from the alexa simulator always get caught up here ...
    console.info('The raw request body has already been parsed');
    var certUrl, er, error, signature
    certUrl = req.headers.signaturecertchainurl
    signature = req.headers.signature
    console.info(`CERTURL: {certUrl} {er} {error} {signature}`);
    verifier(certUrl, signature, JSON.stringify(req.body), function(er) {
      if (er) {
        res.status(400).json({ status: 'failure', reason: er })
        console.info('ERROR: ' + er);
      } else {
        next()
      }
    })
    console.info('finished');
    //return res.status(400).json({ status: 'failure', reason: er })
  }
```

PS: yes i've read the documentation and i don't have any other middleware parser in my code before the alexa verifier.

**Comment by tejashah88** [comment]
Hmm, it seems that there's some pre-processing of the body of the request, which is why the verifier module _intentionally_ fails here. Could you post the output of `req.body` and `req.rawBody` just before your logic?

Also, it's been a few years since I've done Alexa Skill development, so it's very possible their stuff has changed between then and now. Could you describe what the development environment is like? (libraries used, if it's a web-based coding interface, etc)

**Comment by EeeDotZee** [comment]
I will send you the output of the `req.body` via mail as i'm not sure if it contains sensitive information about my account.

As my setup I'm using Jovo V4 with the Express JS module running. Maybe the Jovo ExpressJS is already parsing the body. By the way as i said, when i just don't check for the parsed body your verifier works fine.

**Comment by tejashah88** [comment]
@EeeDotZee So I took a look at the source code regarding the Express.js integration with the Jovo v4 framework, and assuming that you were following [their guide for express integration](https://www.jovo.tech/marketplace/server-express), they load the JSON parser from`body-parser` via [`express.json()`](https://github.com/jovotech/jovo-framework/blob/dba71b943c3ff57afce1657d382b7a2d24bb7896/integrations/server-express/src/index.ts) before you can load any other middleware, which is causing your problem.

The fix seems simple however. Their so-called `Webhook` class that you import from the `@jovotech/server-express` module is really just a wrapper for an express app, which means that it's _trivial_ to implement your own version of `Webhook`.

Old code:
```js
import { ExpressJs, Request, Response, Webhook } from '@jovotech/server-express';
```

New code (UNTESTED):
```js
// In a separate file...
import express from 'express';
import verifier from 'alexa-verifier-middleware';

const server: express.Application = express();
server.use(verifier);
server.use(express.json());

export { server as Webhook };
```

```js
// In your main file...
import { Webhook } from 'path/to/custom/express/webhook';
import { ExpressJs, Request, Response } from '@jovotech/server-express';
```

Let me know if that works for you.

**Comment by tejashah88** [comment]
@EeeDotZee Any update on this?

**Comment by tejashah88** [comment]
Closing. If this still needs attention, feel free to re-open
