### ISSUE TITLE
Uncaught exception when testing without including a signature on the request

### ISSUE THREAD

**Issue by strttn** [alexa-js/alexa-verifier-middleware#5]
Hi there.

First up, thanks for the module. Much appreciated.

I was just testing the auth process through Postman by sending a request to my endpoint without any authorisation headers. As expected the module fails the authorisation and sends back a 401. However, it also crashes my app in the process. Here is the output:

```
3:14:07 PM web.1 |  Node app is running on port 5000
3:14:12 PM web.1 |  error validating the alexa cert: signature is not base64 encoded
3:14:12 PM web.1 |  _http_outgoing.js:335
3:14:12 PM web.1 |      throw new Error('Can\'t set headers after they are sent.');
3:14:12 PM web.1 |      ^
3:14:12 PM web.1 |  Error: Can't set headers after they are sent.
3:14:12 PM web.1 |      at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
```

Is there something I'm missing or something else I should do to prevent this happening or are you able to amend the module so that it doesn't crash in this instance?

Thanks very much.

**Comment by dblock** [comment]
This could be something in your own setup, where something else sends a header before the middleware is invoked. Try to see what's above that?

**Comment by strttn** [comment]
Thanks for the quick response.

It was that container.js was attempting to send back a second response in the event that there was no signaturecertchainurl present on the request.

I have created a pull request for the fix.

**Comment by mreinstein** [comment]
fixed with f284b6d

thanks for catching this issue! Please feel free to re-open if this doesn't solve the issue.

**Comment by mreinstein** [comment]
@tejashah88 can you please run `npm publish` on this? I don't have permissions on this npm package.

**Comment by tejashah88** [comment]
Already done! I've also added you on npm as well.

**Comment by dblock** [comment]
Teamwork!
