### ISSUE TITLE
Publish version in NPMJS

### ISSUE THREAD

**Issue by Reni88** [alexa-js/alexa-verifier-middleware#54]
Hi,

I would like to know when is the plan to publish the latest version of the package in NPMJS?
We have made some updates recently going to 2.0.3 but NPMJS is still in 2.0.2.

Thanks and regards!

**Comment by tejashah88** [comment]
@dblock Can you work on this? I'm currently out of town and won't be able to do this myself.

**Comment by dblock** [comment]
I'll queue it up but I don't even use this library anymore ;) Maybe @mreinstein is around?

**Comment by mreinstein** [comment]
what is there to "queue"?   Just publish it?

**Comment by dblock** [comment]
I meant my queue for things to do this weekend ;)

**Comment by mreinstein** [comment]
published as 2.0.3
